algoritmo " Exercicio 5 Area do Triangulo"
// Função : Peça a base e a altura de um triangulo e calcule sua area usando
// area = (base x altura) / 2
// Autor : Renan Delfino
// Data : 17/09/2026
// Seção de Declarações 
var
   base, altura, area: real
inicio
      escreva(" digitar a base do triangulo ")
      leia(base)
      escreva(" digitar a altura do triangulo ")
      leia(altura)
      area <- (base * altura) / 2
      escreva(" A area do triangulo e: ", area)
      
fimalgoritmo
