algoritmo "Exercicio 2 nome e idade"
// Fun??o : peca o nome e a idade da pessoa // ele pede informcao ao o usuario
// o nome e a idade e aparece na tela do mesmo
// Autor :  Renan Delfino
// Data : 10/09/2026
// Seção de Declarações 
var
   nome: caractere
   idade: inteiro
   informacao: caractere

  inicio
      escreval (" Seja bem vindo ")
      escreva (" digite seu nome ")
      Leia(nome)
      escreva (" digite sua idade ")
      Leia(idade)
      escreval("informacao")
      escreval("nome: ", nome)
      escreval("idade: ", idade)
      
 fimalgoritmo
