algoritmo "aula 3 exercicio 3"
// Função : mostrar o sistema fazer o dobro e triplo
// Autor :  Renan Delfino
// Data : 11/09/2026
// Seção de Declarações 
var
   numero, dobro, triplo: inteiro
inicio
      escreva(" digite um numero ")
      leia(numero)
      dobro <- numero * 2
      triplo <- numero * 3
      escreval("O dobro de ", numero, " e: ", dobro)
      escreval("O triplo de ", numero, " e: ", triplo)
fimalgoritmo
