algoritmo "Aula 4 Exercicio 1"
// Função : Qual é Maior ?
// Autor : Renan Delfino
// Data : 17/09/2026
// Seção de Declarações 
var
   numero1, numero2: inteiro
inicio
      escreva(" digite o primeiro numero ")
      leia(numero1)
      escreva(" digite o segundo numero ")
      leia(numero2)
      se numero1 > numero2 entao
      escreva(" O primeiro numero e maior. ")
      senao se numero2 > numero1 entao
      escreva(" o segundo numero e maior. ")
      senao
           escreva(" os numeros sao iguais. ")
      fimse
fimalgoritmo
