algoritmo "Aula 4 exercicio 2"
// Função : Peça a idade. Se for 18 ou mais, mostre que a pessoa pode entrar;
// caso contrario, mostre que nao pode.
// Autor : Renan Delfino
// Data : 17/09/2026
// Seção de Declarações 
var
   idade: inteiro
inicio
      escreva(" digite sua idade ")
      leia(idade)
      se idade >= 18 entao
      escreva(" Pode Entrar ")
      senao
      escreva(" Nao Pode Entrar ")
      fimse
fimalgoritmo
