algoritmo "Rotina"
// Função : Exercicio 2 - Crie um programa que mostre na tela 5 passos simples
// da sua rotina ao acordar
// Autor : Renan Delfino
// Data : 08/09/2026
// Seção de Declarações
var

inicio
      escreval (" acordei ")
      escreval (" Levantei ")
      escreval (" escovei os dentes ")
      escreval (" tomei o cafe ")
      escreval (" escovei os dentes e tomei banho ")
fimalgoritmo
