algoritmo "Exercicio 3"
// Função : pequena ficha
// Autor : Renan Delfino
// Data : 10/09/2026
// Seção de Declarações 
var
   Nome: Caractere
   Idade: Inteiro
   Profissao: caractere
   Ficha: caractere
inicio
      Escreval (" Seja bem vindo ")
      escreva (" digite seu nome ")
      Leia(nome)
      escreva(" digite sua idade ")
      Leia(idade)
      escreva(" qual sua profissao ")
      Leia(profissao)
      escreval("")
      Escreval("ficha")
      escreval("nome: ", nome)
      escreval("idade: ", idade)
      escreval("profissao", profissao)
fimalgoritmo
